name: Selenium Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install project dependencies, including Selenium

      - name: Install Chrome Driver via apt
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-chromedriver

      - name: Run Selenium tests
        env:
          DISPLAY: :99.0
        run: |
          Xvfb :99 -screen 0 1024x768x24 &
          python main.py  # Run your Selenium script

